language: generic
sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake clang-3.9 build-essential libc++-dev libc++abi-dev
script: cmake . -DCMAKE_CXX_COMPILER=clang++-3.9 && make && make test
